name: ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
        otp:
          - "26.2.2"
          - "25.3.2"
          - "24.3.4"
        elixir:
          - "1.16.3"
          - "1.15.7"
          - "1.14.5"
          - "1.13.4"
          - "1.12.3"
        exclude:
          - otp: "26.2.2"
            elixir: "1.14.5"
          - otp: "26.2.2"
            elixir: "1.13.4"
          - otp: "26.2.2"
            elixir: "1.12.3"
          - otp: "25.3.2"
            elixir: "1.13.4"
          - otp: "25.3.2"
            elixir: "1.12.3"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            _build
            deps
            vendor
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
